version: '3.8'


services:
  db1:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: nbddb1
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
  db2:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: nbddb2
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - "5433:5433"
    volumes:
      - pg:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pg: